"""add_free_reports_count

Revision ID: 0762fc920ed9
Revises: 8fb93196013f
Create Date: 2026-02-04 18:24:19.485707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0762fc920ed9'
down_revision: Union[str, Sequence[str], None] = '8fb93196013f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('free_reports_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'free_reports_count')
    # ### end Alembic commands ###
