"""add_last_activity_field

Revision ID: 0eb627135282
Revises: ba7cd107ccbd
Create Date: 2026-02-19 18:39:36.170845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eb627135282'
down_revision: Union[str, Sequence[str], None] = 'ba7cd107ccbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('last_activity', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'last_activity')
    # ### end Alembic commands ###
