"""add_project_model

Revision ID: 174f7637b1ed
Revises: 559959a0137b
Create Date: 2026-02-11 19:32:10.600322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '174f7637b1ed'
down_revision: Union[str, Sequence[str], None] = '559959a0137b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('property_manager_name', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Indicates if the instance is active'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_projects_client_not_deleted', 'projects', ['client_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('project_properties',
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('SINGLE_FAMILY', 'DUPLEX', 'SINGLE_STRUCTURE_MULTI_FAMILY', 'MULTI_STRUCTURE', 'COMMERCIAL', name='property_type_enum'), nullable=False),
    sa.Column('number_of_units', sa.Integer(), nullable=False),
    sa.Column('owner_lcc_name', sa.String(length=255), nullable=True),
    sa.Column('year_of_construction', sa.Integer(), nullable=True),
    sa.Column('parcel_number', sa.String(length=255), nullable=True),
    sa.Column('rental_registration_number', sa.String(length=255), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Indicates if the instance is active'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_properties_project_id'), 'project_properties', ['project_id'], unique=False)
    op.create_index('ix_project_properties_project_not_deleted', 'project_properties', ['project_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('property_structures',
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('SINGLE_FAMILY', 'DUPLEX', 'SINGLE_STRUCTURE_MULTI_FAMILY', 'MULTI_STRUCTURE', 'COMMERCIAL', name='property_type_enum'), nullable=False),
    sa.Column('number_of_units', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Indicates if the instance is active'),
    sa.CheckConstraint("type != 'MULTI_STRUCTURE'", name='ck_project_property_no_multi_structure'),
    sa.ForeignKeyConstraint(['property_id'], ['project_properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_structures_property_id'), 'property_structures', ['property_id'], unique=False)
    op.create_index('ix_property_structures_property_not_deleted', 'property_structures', ['property_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('uq_clients_email_not_deleted', 'clients', ['email'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_clients_email_not_deleted', table_name='clients', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_property_structures_property_not_deleted', table_name='property_structures', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_property_structures_property_id'), table_name='property_structures')
    op.drop_table('property_structures')
    op.drop_index('ix_project_properties_project_not_deleted', table_name='project_properties', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_project_properties_project_id'), table_name='project_properties')
    op.drop_table('project_properties')
    op.drop_index('ix_projects_client_not_deleted', table_name='projects', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('projects')
    # ### end Alembic commands ###
