"""create_inspector_model

Revision ID: 17f2221049c8
Revises: 0eb627135282
Create Date: 2026-02-19 21:41:06.718331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17f2221049c8'
down_revision: Union[str, Sequence[str], None] = '0eb627135282'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspectors',
    sa.Column('name', sa.String(length=32), nullable=False, comment='First name of the client'),
    sa.Column('surname', sa.String(length=32), nullable=False, comment='Last name of the client'),
    sa.Column('email', sa.String(length=254), nullable=False, comment='Unique email address for login'),
    sa.Column('phone_number', sa.String(length=16), nullable=True, comment='Phone number of the user'),
    sa.Column('license_number', sa.String(length=255), nullable=False, comment='License number of the inspector'),
    sa.Column('licence_type', sa.Enum('LEAD_CLEARANCE_TECHNICIAN', 'LEAD_INSPECTOR', 'RISK_ASSESSOR', 'PROJECT_DESIGNER', name='inspector_licence_type_enum'), nullable=False),
    sa.Column('issue_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('expiration_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('license_image_key', sa.String(length=512), nullable=True, comment='S3 key for image'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Indicates if the instance is active'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('uq_inspector_email_not_deleted', 'inspectors', ['email'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_inspector_email_not_deleted', table_name='inspectors', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('inspectors')
    # ### end Alembic commands ###
