"""drop calendar_events and add scheduled_date to jobs

Revision ID: 28497f173389
Revises: b1c2d3e4f5g6
Create Date: 2026-03-04 15:01:47.562894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28497f173389'
down_revision: Union[str, Sequence[str], None] = 'b1c2d3e4f5g6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calendar_events_job_id'), table_name='calendar_events')
    op.drop_table('calendar_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_events',
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('scheduled_date', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('note', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('calendar_events_job_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('calendar_events_pkey'))
    )
    op.create_index(op.f('ix_calendar_events_job_id'), 'calendar_events', ['job_id'], unique=False)
    # ### end Alembic commands ###
