"""creating_tables_for_storing_report_form_data

Revision ID: 40add9110cab
Revises: 5eab186f1c67
Create Date: 2026-03-03 00:38:37.615445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40add9110cab'
down_revision: Union[str, Sequence[str], None] = '5eab186f1c67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_events',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('note', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_events_job_id'), 'calendar_events', ['job_id'], unique=False)
    op.create_table('coc_forms',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coc_forms_job_id'), 'coc_forms', ['job_id'], unique=False)
    op.create_table('job_documents',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('s3_key', sa.String(length=512), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_documents_job_id'), 'job_documents', ['job_id'], unique=False)
    op.create_table('units',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_common_area', sa.Boolean(), nullable=False),
    sa.Column('floor_plan_s3_key', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_units_job_id'), 'units', ['job_id'], unique=False)
    op.create_table('rooms',
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_unit_id'), 'rooms', ['unit_id'], unique=False)
    op.create_table('samples',
    sa.Column('coc_form_id', sa.UUID(), nullable=False),
    sa.Column('sample_type', sa.Enum('PAINT_CHIP', 'DUST_WIPE', 'WATER', 'SOIL', name='sample_type_enum'), nullable=False),
    sa.Column('barcode_id', sa.String(length=100), nullable=False, comment='Short sample barcode like "01", "02".'),
    sa.Column('location_description', sa.String(length=512), nullable=True),
    sa.Column('side', sa.String(length=50), nullable=True),
    sa.Column('component', sa.String(length=255), nullable=True),
    sa.Column('soil_area', sa.String(length=100), nullable=True),
    sa.Column('photo_s3_key', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coc_form_id'], ['coc_forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_samples_coc_form_id'), 'samples', ['coc_form_id'], unique=False)
    op.create_table('observations',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.Enum('HAZARD', 'FUTURE_RISK', 'EXCLUSION', name='observation_category_enum'), nullable=False),
    sa.Column('is_exterior', sa.Boolean(), nullable=False),
    sa.Column('component', sa.String(length=255), nullable=False),
    sa.Column('side', sa.String(length=50), nullable=True),
    sa.Column('condition', sa.String(length=255), nullable=True),
    sa.Column('identifiers', sa.String(length=255), nullable=True),
    sa.Column('raw_text', sa.String(length=1024), nullable=True),
    sa.Column('xrf_reading', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observations_job_id'), 'observations', ['job_id'], unique=False)
    op.create_index(op.f('ix_observations_room_id'), 'observations', ['room_id'], unique=False)
    op.create_table('photos',
    sa.Column('observation_id', sa.UUID(), nullable=False),
    sa.Column('s3_key', sa.String(length=512), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photos_observation_id'), 'photos', ['observation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photos_observation_id'), table_name='photos')
    op.drop_table('photos')
    op.drop_index(op.f('ix_observations_room_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_job_id'), table_name='observations')
    op.drop_table('observations')
    op.drop_index(op.f('ix_samples_coc_form_id'), table_name='samples')
    op.drop_table('samples')
    op.drop_index(op.f('ix_rooms_unit_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_units_job_id'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_job_documents_job_id'), table_name='job_documents')
    op.drop_table('job_documents')
    op.drop_index(op.f('ix_coc_forms_job_id'), table_name='coc_forms')
    op.drop_table('coc_forms')
    op.drop_index(op.f('ix_calendar_events_job_id'), table_name='calendar_events')
    op.drop_table('calendar_events')
    # ### end Alembic commands ###
