"""create_token_model

Revision ID: 4b5a6a0f9af0
Revises: b887b0e899b6
Create Date: 2026-02-02 23:18:38.458543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b5a6a0f9af0'
down_revision: Union[str, Sequence[str], None] = 'b887b0e899b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
    sa.Column('jti', sa.String(length=255), nullable=False, comment='JWT ID claim from the token'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='User ID associated with the token'),
    sa.Column('expires_at', sa.Integer(), nullable=False, comment='Token expiration timestamp (Unix time)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blacklist_tokens_expires_at'), 'blacklist_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_blacklist_tokens_jti'), 'blacklist_tokens', ['jti'], unique=True)
    op.create_index(op.f('ix_blacklist_tokens_user_id'), 'blacklist_tokens', ['user_id'], unique=False)
    op.create_index('ix_blacklist_tokens_user_id_expires_at', 'blacklist_tokens', ['user_id', 'expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_blacklist_tokens_user_id_expires_at', table_name='blacklist_tokens')
    op.drop_index(op.f('ix_blacklist_tokens_user_id'), table_name='blacklist_tokens')
    op.drop_index(op.f('ix_blacklist_tokens_jti'), table_name='blacklist_tokens')
    op.drop_index(op.f('ix_blacklist_tokens_expires_at'), table_name='blacklist_tokens')
    op.drop_table('blacklist_tokens')
    # ### end Alembic commands ###
