"""extend_s3_keys_for_equipment_and_inspector

Revision ID: 4de6d396c6ec
Revises: b710e0fa1c3d
Create Date: 2026-02-27 23:44:28.403826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4de6d396c6ec'
down_revision: Union[str, Sequence[str], None] = 'b710e0fa1c3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipments', sa.Column('training_certificate_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='S3 keys for training certificate images'))
    op.alter_column('equipments', 'training_certificate_key',
               existing_type=sa.VARCHAR(length=512),
               comment='S3 key for image (first from training_certificate_keys)',
               existing_comment='S3 key for image',
               existing_nullable=True)
    op.add_column('inspectors', sa.Column('license_image_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='S3 keys for license images'))
    op.alter_column('inspectors', 'license_image_key',
               existing_type=sa.VARCHAR(length=512),
               comment='S3 key for image (first from license_image_keys)',
               existing_comment='S3 key for image',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inspectors', 'license_image_key',
               existing_type=sa.VARCHAR(length=512),
               comment='S3 key for image',
               existing_comment='S3 key for image (first from license_image_keys)',
               existing_nullable=True)
    op.drop_column('inspectors', 'license_image_keys')
    op.alter_column('equipments', 'training_certificate_key',
               existing_type=sa.VARCHAR(length=512),
               comment='S3 key for image',
               existing_comment='S3 key for image (first from training_certificate_keys)',
               existing_nullable=True)
    op.drop_column('equipments', 'training_certificate_keys')
    # ### end Alembic commands ###
