"""remove_previous_keys_s3

Revision ID: 524950887bf1
Revises: 4de6d396c6ec
Create Date: 2026-02-27 23:54:42.555673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '524950887bf1'
down_revision: Union[str, Sequence[str], None] = '4de6d396c6ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipments', 'training_certificate_key')
    op.drop_column('inspectors', 'license_image_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspectors', sa.Column('license_image_key', sa.VARCHAR(length=512), autoincrement=False, nullable=True, comment='S3 key for image (first from license_image_keys)'))
    op.add_column('equipments', sa.Column('training_certificate_key', sa.VARCHAR(length=512), autoincrement=False, nullable=True, comment='S3 key for image (first from training_certificate_keys)'))
    # ### end Alembic commands ###
