"""add_marketing_fields_to_user

Revision ID: 559959a0137b
Revises: 6b87c88eeb7b
Create Date: 2026-02-09 23:00:55.847384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '559959a0137b'
down_revision: Union[str, Sequence[str], None] = '6b87c88eeb7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Определяем тип Enum
    marketing_enum = postgresql.ENUM(
        'GOOGLE', 'SOCIAL_MEDIA', 'REFERRAL', 'OTHER',
        name='marketing_source_enum'
    )

    marketing_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        'users',
        sa.Column(
            'marketing_source',
            marketing_enum,
            nullable=True
        )
    )

    op.add_column(
        'users',
        sa.Column(
            'marketing_source_details',
            sa.String(length=255),
            nullable=True
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'marketing_source_details')
    op.drop_column('users', 'marketing_source')

    marketing_enum = postgresql.ENUM(
        'GOOGLE', 'SOCIAL_MEDIA', 'REFERRAL', 'OTHER',
        name='marketing_source_enum'
    )
    marketing_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
