"""create_equipment_model

Revision ID: 57df05b774f5
Revises: 17f2221049c8
Create Date: 2026-02-19 21:51:47.419590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57df05b774f5'
down_revision: Union[str, Sequence[str], None] = '17f2221049c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipments',
    sa.Column('name', sa.String(length=254), nullable=False),
    sa.Column('manufacturer', sa.String(length=254), nullable=False),
    sa.Column('model', sa.String(length=254), nullable=False),
    sa.Column('serial_number', sa.String(length=254), nullable=False),
    sa.Column('mode', sa.Enum('X_RAY_TUBE', 'RADIOACTIVE_ISOTOPE', name='operation_mode_enum'), nullable=False),
    sa.Column('date_of_radioactive_source', sa.Date(), nullable=True),
    sa.Column('training_certificate_key', sa.String(length=512), nullable=True, comment='S3 key for image'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Indicates if the instance is active'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipments')
    # ### end Alembic commands ###
