"""create_pricing_plan

Revision ID: 64940eae70c7
Revises: 4b5a6a0f9af0
Create Date: 2026-02-04 17:16:53.626692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64940eae70c7'
down_revision: Union[str, Sequence[str], None] = '4b5a6a0f9af0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricing_plans',
    sa.Column('plan', sa.Enum('SOLO_INSPECTOR', 'ENTERPRISE', 'ENTERPRISE_PLUS', name='user_plan_enum'), nullable=False),
    sa.Column('period', sa.Enum('MONTHLY', 'YEARLY', name='billing_period_enum'), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('currency', sa.Enum('USD', name='currency_enum'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan', 'period', name='uq_pricing_plan_period')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pricing_plans')
    # ### end Alembic commands ###
