"""add_onboarding_field_to_user

Revision ID: 6b87c88eeb7b
Revises: 849b6e115dfe
Create Date: 2026-02-09 21:22:42.525277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b87c88eeb7b'
down_revision: Union[str, Sequence[str], None] = '849b6e115dfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_onboarding_completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_onboarding_completed')
    # ### end Alembic commands ###
