"""create_client_model

Revision ID: 849b6e115dfe
Revises: 0762fc920ed9
Create Date: 2026-02-09 17:13:02.073416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '849b6e115dfe'
down_revision: Union[str, Sequence[str], None] = '0762fc920ed9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('name', sa.String(length=32), nullable=False, comment='First name of the client'),
    sa.Column('surname', sa.String(length=32), nullable=False, comment='Last name of the client'),
    sa.Column('email', sa.String(length=254), nullable=False, comment='Unique email address for login'),
    sa.Column('phone_number', sa.String(length=16), nullable=True, comment='Phone number of the user'),
    sa.Column('business_address', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Indicates if the instance is active'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clients')
    # ### end Alembic commands ###
