"""add_plan_period_to_user

Revision ID: 8fb93196013f
Revises: 64940eae70c7
Create Date: 2026-02-04 18:16:52.183530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fb93196013f'
down_revision: Union[str, Sequence[str], None] = '64940eae70c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_plan', sa.Enum('SOLO_INSPECTOR', 'ENTERPRISE', 'ENTERPRISE_PLUS', name='user_plan_enum'), nullable=True))
    op.add_column('users', sa.Column('billing_period', sa.Enum('MONTHLY', 'YEARLY', name='billing_period_enum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'billing_period')
    op.drop_column('users', 'current_plan')
    # ### end Alembic commands ###
