"""created_job_model

Revision ID: b710e0fa1c3d
Revises: 8c52043aa1c1
Create Date: 2026-02-24 16:58:57.053914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b710e0fa1c3d'
down_revision: Union[str, Sequence[str], None] = '8c52043aa1c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('inspector_id', sa.Integer(), nullable=True),
    sa.Column('inspection_type', sa.Enum('PERSONAL_BUSINESS_METING', 'CONSULTATION', 'RISK_ASSESSMENT', 'LIRA', 'CLEARANCE', 'PRE_INSPECTION', 'SAMPLING_OR_RETEST', name='inspection_type_enum'), nullable=False),
    sa.Column('notes', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Indicates if the instance is active'),
    sa.ForeignKeyConstraint(['inspector_id'], ['inspectors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['project_properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_inspector_id'), 'jobs', ['inspector_id'], unique=False)
    op.create_index('ix_jobs_inspector_not_deleted', 'jobs', ['inspector_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_jobs_property_id'), 'jobs', ['property_id'], unique=False)
    op.create_index('ix_jobs_property_not_deleted', 'jobs', ['property_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_jobs_property_not_deleted', table_name='jobs', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_jobs_property_id'), table_name='jobs')
    op.drop_index('ix_jobs_inspector_not_deleted', table_name='jobs', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_jobs_inspector_id'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
