"""create_user_model

Revision ID: b887b0e899b6
Revises: 
Create Date: 2026-02-02 22:18:46.538666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b887b0e899b6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('name', sa.String(length=32), nullable=False, comment='First name of the user'),
    sa.Column('surname', sa.String(length=32), nullable=False, comment='Last name of the user'),
    sa.Column('email', sa.String(length=254), nullable=False, comment='Unique email address for login'),
    sa.Column('password', sa.String(length=512), nullable=False, comment='Hashed password'),
    sa.Column('phone_number', sa.String(length=16), nullable=True, comment='Phone number of the user'),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'INSPECTOR', 'SOLO_OPERATOR', name='user_role_enum'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Indicates if the instance is active'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
