"""add_inspector_id_toequipment

Revision ID: e52818476f68
Revises: 524950887bf1
Create Date: 2026-02-28 00:02:14.057315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e52818476f68'
down_revision: Union[str, Sequence[str], None] = '524950887bf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipments', sa.Column('inspector_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_equipments_inspector_id'), 'equipments', ['inspector_id'], unique=False)
    op.create_foreign_key(None, 'equipments', 'inspectors', ['inspector_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'equipments', type_='foreignkey')
    op.drop_index(op.f('ix_equipments_inspector_id'), table_name='equipments')
    op.drop_column('equipments', 'inspector_id')
    # ### end Alembic commands ###
