class BaseDomainFileException(Exception): ...


class EmptyFileNameException(BaseDomainFileException): ...


class EmptyFileException(BaseDomainFileException): ...


class UnknownFiletypeException(BaseDomainFileException): ...


class IncorrectFileSizeException(BaseDomainFileException): ...


class FileUploadException(BaseDomainFileException): ...
