name: Deploy Lambda with SAM

on:
  push:
    branches:
      - main
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Define Environment
        id: env-def
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "ENV_MODE=prod" >> $GITHUB_ENV
            echo "STACK_NAME=Pbpilot-prod" >> $GITHUB_ENV
          else
            echo "ENV_MODE=dev" >> $GITHUB_ENV
            echo "STACK_NAME=Pbpilot-dev" >> $GITHUB_ENV
          fi

      - name: Install UV
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install AWS SAM CLI
        run: |
          uv pip install --system aws-sam-cli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Export dependencies to requirements.txt
        run: uv export --format requirements.txt --no-dev > requirements.txt

      - name: SAM Build
        run: sam build

      - name: SAM Deploy
        run: |
          sam deploy \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --stack-name ${{ env.STACK_NAME }} \
            --capabilities CAPABILITY_IAM \
            --region ${{ secrets.AWS_REGION }} \
            --parameter-overrides EnvMode=${{ env.ENV_MODE }}
