name: Deploy changes to Dev

on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
jobs:
  deploy-to-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get ssh key
        run: |
          echo "${{ secrets.SSH_KEY }}" > ../id_ed25519
          chmod 600 ../id_ed25519

      - name: Get repo name
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_ENV

      - name: Get ec2 instance IP
        run: |
          PUBLIC_IP=$(aws ec2 describe-instances \
            --filters "Name=tag:Name,Values=${{ env.REPO_NAME }}-${{ env.ENVIRONMENT }}" "Name=instance-state-name,Values=running" \
            --query "Reservations[0].Instances[0].PublicIpAddress" \
            --output text)

          echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV

      - name: Deploy to the server
        run: |
          ssh -o StrictHostKeyChecking=no -i ../id_ed25519 ubuntu@${{ env.PUBLIC_IP }} << 'EOF'
          cd ~/${{ env.REPO_NAME }}
          git fetch origin
          git reset --hard origin/main
          git checkout main
          git pull
          echo "${{ secrets.ENV }}" > .env
          # sudo chmod 777 --recursive db-data
          docker compose down 
          docker system prune -af && docker builder prune --all --force 
          docker compose up -d --build
          timeout 50 docker compose logs -f --tail 300 || true
          EOF
